{
    # App information
    'name': "Odoo Magento 2 Connector",
    'version': '13.1.0.0',
    'category': 'Connector',
    'license': 'OPL-1',
    'summary': 'Odoo Magento 2 Connector helps you integrate your Magento 2.x website with Odoo '
               'and automates various operations between Odoo and Magento.',
    # Author
    'author': 'Emipro Technologies Pvt. Ltd.',
    'website': 'http://www.emiprotechnologies.com/',
    'maintainer': 'Emipro Technologies Pvt. Ltd.',

    # Dependencies
    'depends': ['auto_invoice_workflow_ept', 'common_connector_library'],

    # Views
    'data': [
        'security/security.xml',
        'data/import_order_status.xml',
        'views/magento_instance_view.xml',
        'views/magento_website_view.xml',
        'views/magento_storeview_view.xml',
        'views/magento_inventory_locations_view.xml',
        'views/magento_payment_method_view.xml',
        'views/delivery_carrier_view.xml',
        'wizard_views/magento_import_export_operation_view.xml',
        'wizard_views/magento_cron_configuration_view.xml',
        'wizard_views/res_config_magento_instance.xml',
        'wizard_views/res_config_settings.xml',
        'data/ir_sequence_data.xml',
        'views/magento_product_product_view.xml',
        'views/magento_product_template_view.xml',
        'views/magento_product_image_view.xml',
        'wizard_views/magento_queue_process_wizard_view.xml',
        'views/res_partner_view.xml',
        'views/sale_order_view.xml',
        'views/sale_order_cancel_view.xml',
        'views/magento_order_data_queue_ept.xml',
        'views/view_magento_process_log.xml',
        'views/magento_order_data_queue_line_ept.xml',
        'views/sync_import_magento_product_queue.xml',
        'views/sync_import_magento_product_queue_line.xml',
        'views/magento_customer_data_queue_ept.xml',
        'views/magento_customer_data_queue_line_ept.xml',
        'data/magento_data_cron.xml',
        'data/ir_cron_data.xml',
        'views/stock_picking_view.xml',
        'wizard_views/magento_export_credit_memo.xml',
        'views/account_move_view.xml',
        'views/magento_dashboard_view.xml',
        'views/magento_delivery_carrier.xml',
        'views/financial_status_view.xml',
        'views/magento_product_category_view.xml',
        'views/magento_tax_class.xml',
        'views/magento_attribute_set.xml',
        'views/magento_attribute_group.xml',
        'views/magento_attribute_option.xml',
        'views/magento_product_attribute_view.xml',
        'wizard_views/magento_export_product_ept.xml',
        'report/sale_report.xml',
        'data/ecommerce_data.xml',
        'data/sale_workflow_process_data.xml',
        'data/auto_financial_status.xml',
        'data/update_magento_partner.xml',
        'security/ir.model.access.csv',
    ],

    # Odoo Store Specific

    'images': ['static/description/Odoo-Magento-2-Connector-Cover.jpg'],
    'installable': True,
    'auto_install': False,
    'application': True,
    'live_test_url': 'https://www.emiprotechnologies.com/free-trial?app=odoo-magento2-ept&version=13',
    'price': 379.00,
    'currency': 'EUR',

}
